name: Django Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U django_user -d django_db"
          --health-timeout=5s
          --health-start-period=5s
          --health-retries=3

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Set up the database
    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -U django_user -d django_db; do
          echo "Waiting for PostgreSQL...";
          sleep 2;
        done

    # Step 5: Run database migrations
    - name: Run database migrations
      run: |
        python manage.py migrate
        python manage.py migrate session

    # Step 6: Run Django unit tests
    - name: Run Django tests
      env:
        DATABASE_URL: postgres://django_user:django_password@localhost:5432/django_db
      run: |
        python manage.py test

